
delete from produtosProposta  ;
delete from produtosDocumento  ;
delete from documento ;
delete from proposta ;
delete from pessoa ;
delete from config ;
delete from chaveApi ;
delete from notaProcessada ;
delete from planoPagamento ;
delete from produto ;
delete from usuario ;
delete from empresa ;

drop table produtosDocumento  ;
drop table documento ;
drop table produtosProposta ;
drop table proposta ;
drop table pessoa ;
drop table config ;
drop table chaveApi ;
drop table notaProcessada ;
drop table planoPagamento ;
drop table produto ;
drop table usuario ;
drop table empresa ;
drop table documentoGerado ;
drop table knex_migrations ;
drop table knex_migrations_lock ;
